  
--EXEC DBO.RPT_MAESTRO_EMPLEADOS_RHPAY 1, NULL, NULL, NULL, NULL, 1  
/********************************************************************************************  
    JM  
 SP: RPT_MAESTRO_EMPLEADOS_RHPAY  
    Descripción  : Genera el reporte maestro de empleados, considerando filtros como empresa,   
                      razón social, ubicación, periodo, estado, y usuario.  
    Última Modificación: 20250124  
  
********************************************************************************************/  
CREATE PROCEDURE RPT_MAESTRO_EMPLEADOS_RHPAY (             
@Empresa   INT,             
@RAZON_SOCIAL INT,            
@UBICACION   INT,            
@Periodo   INT,            
@STATUS   CHAR(1),            
@nUsuario INT             
)            
AS             
BEGIN            
            
DECLARE  @FIN_ANIO_ANTERIOR SMALLDATETIME            
  ,@FIN_ANIO_ACTUAL SMALLDATETIME            
  ,@INI_ANIO_ACTUAL SMALLDATETIME            
  ,@INI_ANIO_ANTERIOR  SMALLDATETIME            
            
  SELECT @FIN_ANIO_ANTERIOR = CONVERT(SMALLDATETIME,  LTRIM(RTRIM(STR(  YEAR(DATEADD(YY,-1,GETDATE() ) ) )))  +'1231' )            
  SELECT @FIN_ANIO_ACTUAL = CONVERT(SMALLDATETIME,  LTRIM(RTRIM(STR(  YEAR(GETDATE()) )))  +'1231' )            
            
  SELECT @INI_ANIO_ANTERIOR = CONVERT(SMALLDATETIME,  LTRIM(RTRIM(STR(  YEAR(DATEADD(YY,-1,GETDATE() ) ) )))  +'0101' )            
  SELECT @INI_ANIO_ACTUAL = CONVERT(SMALLDATETIME,  LTRIM(RTRIM(STR(  YEAR(GETDATE()) )))  +'0101' )            
            
            
  --SELECT @FIN_ANIO_ANTERIOR,@FIN_ANIO_ACTUAL            
            
  SELECT T1.CLA_TRAB            
 , DBO.fnNombreCompletoTrab(T1.CLA_EMPRESA,T1.CLA_TRAB) AS NOMBRE            
 ,T1.CURP            
 ,T1.RFC            
 ,T1.NUM_IMSS            
 ,LTRIM(RTRIM(T2.NOM_PUESTO)) AS NOM_PUESTO            
 ,LTRIM(RTRIM(T4.CLA_CENTRO_COSTO)) AS CLA_CENTRO_COSTO            
 ,LTRIM(RTRIM(T4.NOM_CENTRO_COSTO)) AS NOM_CENTRO_COSTO            
 ,LTRIM(RTRIM(T1.CLA_UBICACION_BASE )) AS CLA_UBICACION            
 ,LTRIM(RTRIM(T13.NOM_UBICACION )) AS NOM_UBICACION            
 ,LTRIM(RTRIM(T1.CLA_DEPTO )) AS CLA_DEPTO            
 ,LTRIM(RTRIM(T11.NOM_DEPTO )) AS NOM_DEPTO          
 ,LTRIM(RTRIM(T12.NOM_PERIODO )) AS NOM_PERIODO            
 ,T1.SUELDO_INT            
 ,T1.SUELDO_DIA            
 ,T1.SUELDO_MENSUAL            
 ,T1.CLA_RAZON_SOCIAL          
 ,T14.NOM_RAZON_SOCIAL            
 ,t1.CLA_REG_IMSS           
 ,t15.NOM_REG_IMSS             
 ,LTRIM(RTRIM(T5.NOM_CLASIFICACION)) AS NOM_CLASIFICACION            
 ,dbo.fnObtieneRoll( t1.CLA_TRAB, t1.CLA_EMPRESA, GETDATE()) AS ROLL             
 ,LTRIM(RTRIM(T6.NOM_BANCO)) AS NOM_BANCO            
 ,t1.CTA_BANCO  AS CUENTA            
 ,LTRIM(RTRIM(T3.NOM_FORMA_PAGO)) AS NOM_FORMA_PAGO            
 ,t1.CLABE_INTERBANCARIA          
 ,CONVERT(VARCHAR,T1.FECHA_ING,103) AS FECHA_ING             
 ,CONVERT(VARCHAR,T1.fecha_ing_grupo,103) AS FECHA_ING_GRUPO             
 ,T1.CTA_CORREO            
 ,T1.NUM_CTA_DESPENSA            
 ,dbo.fnCalcAntig(T1.ANTIG_BASE,ISNULL(T1.FECHA_ING_GRUPO,t1.FECHA_ING),GETDATE() ) AS ANTIG            
 ,CASE t1.sind WHEN 1 THEN 'SINDICALIZADO' ELSE 'NO SINDICALIZADO' END AS SIND            
 ,T1.CRED_INF            
 --,CASE WHEN T1.VALOR_CREDITO_INFO IN(1,2,3,6) THEN '%' WHEN T1.VALOR_CREDITO_INFO = 4 THEN 'VSM' WHEN t1.valor_credito_info =  5 THEN  'CF' ELSE '' END AS TIPOINFO            
 ,CASE WHEN T1.VALOR_CREDITO_INFO IN(1,2,3) THEN '%' WHEN T1.VALOR_CREDITO_INFO = 4 THEN 'Cuota Monetaria' WHEN t1.valor_credito_info =  5 THEN  'Factor de descuento' WHEN t1.valor_credito_info =  6 THEN  'Tasa INFONAVIT' ELSE '' END AS TIPOINFO          
  
 ,T1.VALOR_TASA_INFO AS TASAINFO            
 ,(SELECT NOM_CONTRATO  FROM dbo.RH_TIPO_CONTRATO WHERE CLA_CONTRATO = T1.TIPO_CONTRATO ) AS EVENTUAL_PLANTA            
 ,T1.AP_PATERNO AS PATERNO            
 ,T1.AP_MATERNO AS MATERNO            
 ,T1.NOM_TRAB AS NOM_TRAB             
 ,t1.CALLE AS CALLE            
 ,T1.COLONIA AS COLONIA         
 ,T1.DOMICILIO_FISCAL_RECEPTOR AS CP_FISCAL ------ JM SE AGREGA CODIGO FISCAL DEL TRAB 20241023        
 ,T1.CP_STR AS CODIGO_POSTAL         
 ,T1.CIUDAD AS CIUDAD            
 ,T1.DELEGACION AS MUNICIPIO            
 ,T1.NACIONALIDAD AS NACIONALIDAD        
 , CASE ------------ JM SE AGREGA CASE PARA CORREGIR COLUMA PAIS        
    WHEN UPPER(T1.NACIONALIDAD) LIKE 'MEXICAN%' THEN 'MEXICO'         
    ELSE 'OTRO'         
END AS PAIS        
 --,CASE WHEN T1.NACIONALIDAD = 'MEXICANO' THEN 'MEXICO' ELSE 'OTRA' END  AS PAIS            
 ,T1.TELEFONO AS TELEFONO            
 ,T1.FECHA_NAC AS FECHA_NACIMIENTO            
 ,T1.SEXO AS GENERO            
 ,DBO.fnNumLetra(T1.SUELDO_MENSUAL,1) AS SUELDO_LETRA,    
    -- JM Se agrego columna de la tabla de prestaciones 2024-10-02    
 T7.CLA_TAB_PRE,    
 T7.NOM_TAB_PRE,    
  -- JM SE AGREGA COLUMNA PARA FONDO DE AHORRO 20241023        
  dbo.Fn_FDOCJA_AHORRO(T1.CLA_EMPRESA, T1.CLA_TRAB, 2) AS FDO_AHORRO,           
  -- JM SE AGREGA COLUMNA PARA CAJA DE AHORRO 20241023          
  dbo.Fn_FDOCJA_AHORRO(T1.CLA_EMPRESA, T1.CLA_TRAB, 3)AS CAJA_AHORRO,          
 --,ISNULL(T10.NOM_AHORRO, 'SIN FONDO ASIGNADO') AS FONDO_AHORRO_EMPLEADO            
 CONVERT(VARCHAR,T1.FECHA_BAJA ,103) AS FECHA_BAJA            
 ,(CASE T1.STATUS_TRAB  WHEN 'A' THEN 'ACTIVO' ELSE 'BAJA' END) AS ESTATUS_TRAB            
 ,ISNULL((SELECT NOM_TIPO_MOV FROM RH_TIPO_MOV WHERE CLA_EMPRESA = T1.CLA_EMPRESA             
     AND CLA_TIPO_MOV = ISNULL( (SELECT MAX(CLA_TIPO_MOV) FROM RH_HIST_LABORAL WHERE CLA_TRAB =T1.CLA_TRAB   AND FECHA_MOV = T1.Fecha_Baja ) ,            
           (SELECT MAX(CLA_TIPO_MOV) FROM RH_NEGOCIA_FINIQUITO WHERE CLA_TRAB =T1.CLA_TRAB   AND FECHA_BAJA = T1.Fecha_Baja  )            
           )), '') AS CAUSA_BAJA,        
 T1.CUADRO_NETO, ---SE AGREGO EL CAMPO CUADRO_NETO PARA 02/07/2024    JM  
 ------- SE AGREGA CHECK DE EXPEDIENTE DE COLAB QUE INDICAN SI APLICAN PARA NÓMINA, PTU, FA, SEGURO Y DECLARACIÓN JM  
 ----CASE PARA MOSTRAR EN REPOTE SI APLICAN O NO JM  
CASE   
    WHEN T1.CALC_NOMINA = 1 THEN 'SI APLICA' ELSE 'NO APLICA'   
END AS APLICA_NOMINA,  
CASE   
    WHEN T1.APLICA_PTU = 1 THEN 'SI APLICA' ELSE 'NO APLICA'   
END AS APLICA_PTU,  
CASE   
    WHEN T1.APLICA_FA = 1 THEN  'SI APLICA' ELSE 'NO APLICA'   
END AS APLICA_FA,  
CASE   
    WHEN T1.APLICA_IMSS = 1 THEN  'SI APLICA' ELSE 'NO APLICA'   
END AS APLICA_IMSS,  
CASE   
    WHEN T1.APLICA_DEC = 1 THEN 'SI APLICA' ELSE 'NO APLICA'   
END AS APLICA_DECARACION,  
CASE   
    WHEN T1.APLICA_DEC_SUELDOS = 1 THEN 'SI APLICA' ELSE 'NO APLICA'    
END AS APLICA_DECARACION_SUE  
             
FROM RH_TRAB T1            
INNER JOIN RH_PUESTO T2            
ON T1.CLA_EMPRESA = T2.CLA_EMPRESA            
AND T1.CLA_PUESTO = T2.CLA_PUESTO            
INNER JOIN dbo.RH_FORMA_PAGO T3            
ON T1.CLA_EMPRESA = T3.CLA_EMPRESA            
AND T1.CLA_FORMA_PAGO = T3.CLA_FORMA_PAGO            
INNER JOIN dbo.RH_CENTRO_COSTO T4            
ON T1.CLA_EMPRESA = T4.CLA_EMPRESA            
AND T1.CLA_CENTRO_COSTO = T4.CLA_CENTRO_COSTO            
INNER JOIN dbo.RH_CLASIFICACION T5            
ON T1.CLA_EMPRESA = T5.CLA_EMPRESA            
AND T1.CLA_CLASIFICACION = T5.CLA_CLASIFICACION            
LEFT JOIN RH_BANCO T6             
ON T1.CLA_BANCO = T6.CLA_BANCO            
INNER JOIN dbo.RH_UBICACION T8            
ON T1.CLA_EMPRESA = T8.CLA_EMPRESA            
AND T1.CLA_UBICACION_BASE = T8.CLA_UBICACION            
          
INNER JOIN dbo.RH_DEPTO  T11            
ON T1.CLA_EMPRESA = T11.CLA_EMPRESA            
AND T1.CLA_DEPTO = T11.CLA_DEPTO             
INNER JOIN RH_PERIODO T12            
ON T1.CLA_PERIODO = T12.CLA_PERIODO             
AND T1.CLA_EMPRESA =T12.CLA_EMPRESA             
INNER JOIN RH_UBICACION T13            
ON T1.CLA_UBICACION_BASE  = t13.CLA_UBICACION             
AND T1.CLA_EMPRESA = T13.CLA_EMPRESA             
INNER JOIN RH_RAZON_SOCIAL T14          
ON t1.CLA_RAZON_SOCIAL = T14.CLA_RAZON_SOCIAL           
AND T1.CLA_EMPRESA =T14.CLA_EMPRESA           
INNER JOIN RH_REG_IMSS T15          
ON t1.CLA_REG_IMSS = T15.CLA_REG_IMSS           
AND T1.CLA_EMPRESA =T15.CLA_EMPRESA      
INNER JOIN RH_ENC_TAB_PRESTAC T7   -- JM Se agrego INNER JOIN de la tabla de prestaciones 2024-10-02    
ON T1.CLA_TAB_PRE = T7.CLA_TAB_PRE      
AND T1.CLA_EMPRESA =T7.CLA_EMPRESA     
    
          
            
WHERE T1.CLA_EMPRESA = @Empresa            
AND (T1.CLA_RAZON_SOCIAL = @RAZON_SOCIAL OR @RAZON_SOCIAL IS null)            
AND (T1.CLA_UBICACION_BASE = @UBICACION OR @UBICACION IS null)            
AND (T1.CLA_PERIODO = @Periodo OR @Periodo IS null)            
AND (T1.STATUS_TRAB = @STATUS OR ISNULL(@STATUS,'') = '')            
AND DBO.fnc_ValidaSeguridadStd(T1.CLA_EMPRESA,@nUsuario,T1.CLA_UBICACION_BASE,T1.CLA_dEPTO,T1.CLA_PERIODO) > 0             
ORDER BY T1.CLA_TRAB            
            
            
            
END  