Execute dbo.sp_baja_variables_trabajador 'LS', '     19459', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19073', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19563', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19914', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19229', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18959', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19468', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19008', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19042', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19680', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19124', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19323', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19267', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19662', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18150', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     61273', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19601', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19314', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19189', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     17589', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     21130', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19847', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18352', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19448', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19752', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19057', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18865', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19812', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19351', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18499', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19394', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18217', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19958', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19225', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19471', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19499', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19367', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19676', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18754', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18317', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19319', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18721', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19505', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19885', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18487', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18977', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18667', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     21056', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     17061', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18906', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18897', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19615', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18831', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19053', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19338', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19411', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     17279', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19522', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19478', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18774', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19362', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18660', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18727', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19512', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19155', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18510', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19330', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19121', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19819', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19548', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19425', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19433', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18605', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18957', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19333', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     79174', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19783', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19310', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18313', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19742', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19285', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19704', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18477', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18870', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19786', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19111', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19558', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19963', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19693', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19092', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     17306', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     17648', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     21267', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19199', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18549', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19540', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18438', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19596', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18958', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19213', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19464', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19369', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19543', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19244', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     21307', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19536', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19469', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19353', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     21283', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18741', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19151', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18596', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     21371', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19139', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18742', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19365', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     66800', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19747', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     18916', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19100', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19732', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19853', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     21214', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19739', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19195', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19515', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19049', 5
Execute dbo.sp_baja_variables_trabajador 'LS', '     19487', 5
