Declare
   @w_desc_error              Varchar( 250),
   @w_Error                   Integer,
   @w_linea                   Integer;

Begin
   Set nocount       off
   Set Xact_Abort    On
   Begin Transaction
      Begin Try
Update a Set    variable_trabajador = 11530.75 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19459'
Update a Set    variable_trabajador = 16196.64 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19073'
Update a Set    variable_trabajador = 8157.01 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19563'
Update a Set    variable_trabajador = 1813.3 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19914'
Update a Set    variable_trabajador = 8705.66 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19229'
Update a Set    variable_trabajador = 17547.74 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18959'
Update a Set    variable_trabajador = 7251.92 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19468'
Update a Set    variable_trabajador = 4863.83 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18056'
Update a Set    variable_trabajador = 8405.54 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19008'
Update a Set    variable_trabajador = 9613.51 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19042'
Update a Set    variable_trabajador = 14923.22 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19680'
Update a Set    variable_trabajador = 12650.58 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19124'
Update a Set    variable_trabajador = 2075.16 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19312'
Update a Set    variable_trabajador = 1446.23 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19323'
Update a Set    variable_trabajador = 5818.67 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19267'
Update a Set    variable_trabajador = 5339.39 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19662'
Update a Set    variable_trabajador = 11568.13 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18150'
Update a Set    variable_trabajador = 2750.86 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%61273'
Update a Set    variable_trabajador = 3209.04 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19601'
Update a Set    variable_trabajador = 5444.81 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19314'
Update a Set    variable_trabajador = 7966.78 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19189'
Update a Set    variable_trabajador = 6133.55 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%17589'
Update a Set    variable_trabajador = 5477.02 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%21130'
Update a Set    variable_trabajador = 7714.8 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19847'
Update a Set    variable_trabajador = 10046.9 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18352'
Update a Set    variable_trabajador = 4996.31 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18756'
Update a Set    variable_trabajador = 7427.09 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19448'
Update a Set    variable_trabajador = 19239.74 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19752'
Update a Set    variable_trabajador = 6720.11 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19057'
Update a Set    variable_trabajador = 8522.97 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18865'
Update a Set    variable_trabajador = 5036.08 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19812'
Update a Set    variable_trabajador = 5781.37 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19351'
Update a Set    variable_trabajador = 4124.84 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18499'
Update a Set    variable_trabajador = 7348.32 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19394'
Update a Set    variable_trabajador = 3275.44 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18217'
Update a Set    variable_trabajador = 2006.73 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19958'
Update a Set    variable_trabajador = 8967.17 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19225'
Update a Set    variable_trabajador = 1835.91 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19471'
Update a Set    variable_trabajador = 15109.15 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19499'
Update a Set    variable_trabajador = 1779.6 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19367'
Update a Set    variable_trabajador = 5024.09 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19676'
Update a Set    variable_trabajador = 3344.67 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18754'
Update a Set    variable_trabajador = 3912.45 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18317'
Update a Set    variable_trabajador = 7985.13 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19319'
Update a Set    variable_trabajador = 1997.41 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18721'
Update a Set    variable_trabajador = 7809.27 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19505'
Update a Set    variable_trabajador = 10638.25 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19885'
Update a Set    variable_trabajador = 1714.37 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18487'
Update a Set    variable_trabajador = 10349.54 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18977'
Update a Set    variable_trabajador = 9351.84 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18667'
Update a Set    variable_trabajador = 19367.78 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18614'
Update a Set    variable_trabajador = 10015.5 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%21056'
Update a Set    variable_trabajador = 12069.69 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%17061'
Update a Set    variable_trabajador = 10977.11 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18906'
Update a Set    variable_trabajador = 2422.76 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18897'
Update a Set    variable_trabajador = 5839.3 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19615'
Update a Set    variable_trabajador = 5483.68 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18831'
Update a Set    variable_trabajador = 6974.56 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19053'
Update a Set    variable_trabajador = 15628.39 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19338'
Update a Set    variable_trabajador = 12772.91 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19411'
Update a Set    variable_trabajador = 10462.32 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%17279'
Update a Set    variable_trabajador = 10734.5 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19522'
Update a Set    variable_trabajador = 9238.43 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19478'
Update a Set    variable_trabajador = 14118.7 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18774'
Update a Set    variable_trabajador = 9587.7 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19362'
Update a Set    variable_trabajador = 1536.11 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18660'
Update a Set    variable_trabajador = 8791.34 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18727'
Update a Set    variable_trabajador = 10417.08 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19512'
Update a Set    variable_trabajador = 6366.59 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19155'
Update a Set    variable_trabajador = 12143.66 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18510'
Update a Set    variable_trabajador = 7682.36 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19330'
Update a Set    variable_trabajador = 2056.65 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19121'
Update a Set    variable_trabajador = 6592.5 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19819'
Update a Set    variable_trabajador = 2278.22 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19548'
Update a Set    variable_trabajador = 8964.59 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19425'
Update a Set    variable_trabajador = 8446.58 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19433'
Update a Set    variable_trabajador = 1770.57 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18605'
Update a Set    variable_trabajador = 8239.51 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18957'
Update a Set    variable_trabajador = 7721.85 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19333'
Update a Set    variable_trabajador = 1873.39 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%79174'
Update a Set    variable_trabajador = 8576.36 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18853'
Update a Set    variable_trabajador = 9921.94 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19783'
Update a Set    variable_trabajador = 7224.11 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%21124'
Update a Set    variable_trabajador = 11049.32 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19310'
Update a Set    variable_trabajador = 5622.23 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18313'
Update a Set    variable_trabajador = 8622.38 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19742'
Update a Set    variable_trabajador = 8656.37 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19285'
Update a Set    variable_trabajador = 10622.41 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19704'
Update a Set    variable_trabajador = 11150.96 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18477'
Update a Set    variable_trabajador = 9497.33 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18870'
Update a Set    variable_trabajador = 9463.79 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19786'
Update a Set    variable_trabajador = 10569.06 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19111'
Update a Set    variable_trabajador = 10422.42 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19558'
Update a Set    variable_trabajador = 18276.45 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19963'
Update a Set    variable_trabajador = 12523.83 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19409'
Update a Set    variable_trabajador = 15746.82 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19693'
Update a Set    variable_trabajador = 2667.62 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19092'
Update a Set    variable_trabajador = 11363.69 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%17306'
Update a Set    variable_trabajador = 12627.14 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%17648'
Update a Set    variable_trabajador = 5043.12 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%21267'
Update a Set    variable_trabajador = 2669.25 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19199'
Update a Set    variable_trabajador = 7478.34 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18549'
Update a Set    variable_trabajador = 6403.88 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19540'
Update a Set    variable_trabajador = 9926.09 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18438'
Update a Set    variable_trabajador = 10007.86 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19596'
Update a Set    variable_trabajador = 5730.41 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18958'
Update a Set    variable_trabajador = 7173.24 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19213'
Update a Set    variable_trabajador = 8079.05 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19464'
Update a Set    variable_trabajador = 6221 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19369'
Update a Set    variable_trabajador = 7261.79 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19543'
Update a Set    variable_trabajador = 10462.66 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19244'
Update a Set    variable_trabajador = 4024.7 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%21128'
Update a Set    variable_trabajador = 4366.4 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19536'
Update a Set    variable_trabajador = 7365.99 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19469'
Update a Set    variable_trabajador = 8432.23 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19353'
Update a Set    variable_trabajador = 2068.98 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%21283'
Update a Set    variable_trabajador = 4657.26 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18741'
Update a Set    variable_trabajador = 2046.53 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19936'
Update a Set    variable_trabajador = 11477.47 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19151'
Update a Set    variable_trabajador = 10355.35 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18596'
Update a Set    variable_trabajador = 7933 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19139'
Update a Set    variable_trabajador = 2633.65 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18742'
Update a Set    variable_trabajador = 6140.93 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19365'
Update a Set    variable_trabajador = 1801.41 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%66800'
Update a Set    variable_trabajador = 10419.69 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19747'
Update a Set    variable_trabajador = 2394.14 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18916'
Update a Set    variable_trabajador = 5740.21 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19100'
Update a Set    variable_trabajador = 7287.88 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%18858'
Update a Set    variable_trabajador = 13248.36 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19732'
Update a Set    variable_trabajador = 6099.5 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19853'
Update a Set    variable_trabajador = 4661.16 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%21214'
Update a Set    variable_trabajador = 15545.53 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19739'
Update a Set    variable_trabajador = 11029.26 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19195'
Update a Set    variable_trabajador = 7067.45 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19515'
Update a Set    variable_trabajador = 1847.04 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19049'
Update a Set    variable_trabajador = 15642.64 From   variables_trabajador a Join   trabajadores_grales   b On     b.compania   = a.compania And    b.trabajador = a.trabajador And    b.sit_trabajador  = 1 And    a.secuencia       = 5 And    b.trabajador  Like '%19487'

      End Try

      Begin Catch
         Select  @w_Error      = @@Error,
                 @w_linea      = Error_line(),
                 @w_desc_error = Substring (Concat(Error_Message(), ' En Linea ', @w_linea), 1, 200)

      End   Catch

      If @w_error != 0
         Begin
            Select @w_error, @w_desc_error;
            Rollback Transaction
            Goto Salida
         End

   Commit Transaction

Salida:

   Return

End
Go